In [1]:
%useLatestDescriptors
%use dataframe

import java.time.LocalDate
import java.io.File
import org.jetbrains.kotlinx.*
import org.jetbrains.kotlinx.dataframe.api.*
import org.jetbrains.kotlinx.dataframe.io.*

In [2]:
// https://kotlin.github.io/dataframe/data-schemas-in-kotlin-notebook.html#custom-data-schemas
interface Schema{
    val MainIsland : String?
    val Region : String?
    val Province : String?
    val LegislativeDistrict : String?
    val Municipality : String?
    val DistrictEngineeringOffice : String?
    val ProjectId : String?
    val ProjectName : String?
    val TypeOfWork : String?
    val FundingYear: Int?
    val ContractId : String?
    val ApprovedBudgetForContract: Double?
    val ContractCost: Double?
    val ActualCompletionDate: LocalDate?
    val Contractor : String?
    val ContractorCount: Int?
    val StartDate: LocalDate?
    val ProjectLatitude:Double?
    val ProjectLongitude: Double?
    val ProvincialCapital : String?
    val ProvincialCapitalLatitude: Double?
    val ProvincialCapitalLongitude: Double?
}

In [3]:
//https://kotlin.github.io/dataframe/convert.html
    // req 01 - read csv
    val path = "D:/01 KEI FILES/Academics and School/DLSU/TERM 4/CSADPRG S11/__MCO/MCO2/dpwh_flood_control_projects.csv"

    val raw = DataFrame
        .readCsv(
            File(path)
        )
    val ogCount = raw.count()
    val conv = raw
            .convert("FundingYear","ContractorCount").with{ it -> it.toString().toIntOrNull() }
            .convert("ApprovedBudgetForContract", "ContractCost", "ProjectLatitude", "ProjectLongitude", "ProvincialCapitalLatitude", "ProvincialCapitalLongitude").with{ it.toString().toDoubleOrNull() }
    val df = conv
        .convertTo<Schema>()
    df.schema().print()

    println("$ogCount")
    println("${df.count()}")
    df

MainIsland: String
Region: String
Province: String
LegislativeDistrict: String
Municipality: String?
DistrictEngineeringOffice: String
ProjectId: String
ProjectName: String
TypeOfWork: String
FundingYear: Int
ContractId: String
ApprovedBudgetForContract: Double?
ContractCost: Double?
ActualCompletionDate: java.time.LocalDate
Contractor: String
ContractorCount: Int
StartDate: java.time.LocalDate
ProjectLatitude: Double
ProjectLongitude: Double
ProvincialCapital: String
ProvincialCapitalLatitude: Double
ProvincialCapitalLongitude: Double
9855
9855

MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,ContractId,ApprovedBudgetForContract,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526268LZ,Construction of Poblacion Flood Contr...,Construction of Flood Mitigation Stru...,2021,21PC0018,96500000.000000,92692943.800000,2022-10-03,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-03-18,18.250910,121.047570,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526368LZ,Construction of Cabicungan Flood Cont...,Construction of Flood Mitigation Stru...,2021,21PC0019,49000000.000000,47521251.300000,2022-11-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.511800,121.078290,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526369LZ,Construction of Sipa-San Mariano Floo...,Construction of Flood Mitigation Stru...,2021,21PC0010,47423180.000000,45942583.670000,2022-11-28,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.270230,121.420220,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561270LZ,Construction of Sta. Filomena Floodwa...,Construction of Flood Mitigation Stru...,2021,21PC0067,9900000.000000,9900000.000000,2022-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.535660,121.080200,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561652LZ,Construction of Sinigpit Flood Contro...,Construction of Flood Mitigation Stru...,2021,21PC0034,4950000.000000,4950000.000000,2022-09-23,ALEPHNORTH PEAK CONSTRUCTION AND DEVE...,1,2021-12-01,18.527230,121.096812,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526367LZ,Construction of Nabuangan River (Upst...,Construction of Flood Mitigation Stru...,2021,21PB0004,39199819.730000,38292917.460000,2022-09-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-02,17.800000,121.315833,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526270LZ,Construction of Nabuangan (Upstream) ...,Construction of Flood Mitigation Stru...,2021,21PB0013,82914680.000000,80309010.270000,2023-04-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-22,17.800278,121.308889,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0005,23519997.480000,22928490.310000,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0004,15678924.680000,15680000.000000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2022,22PB0010,51761907.660000,51762600.000000,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726398LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0009,72375000.000000,72375000.000000,2023-12-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-02-12,17.818642,121.268639,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726655LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0001,24500000.000000,24500000.000000,2023-06-22,GKA ENGINEERING AND CONSTRUCTION,1,2023-02-12,17.799808,121.282278,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00740313LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2023,23P00020,115793907.830000,115800000.000000,2024-02-29,JOMARCANN GENERAL CONSTRUCTION / RODE...,2,2023-04-12,17.819720,121.268330,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620989LZ,Construction of Cabicungan River Basi...,Construction of Flood Mitigation Stru...,2022,22PC0034,49000000.000000,49000000.000000,2022-12-12,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-02-09,18.527890,121.082970,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00640502LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2022,22PC0063,6930000.000000,6827260.010000,2023-09-15,E.C.V. CONSTRUCTION,1,2022-03-25,18.428870,121.189850,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620990LZ,Construction of Sta. Filomena Flood C...,Construction of Flood Mitigation Stru...,2022,22PC0068,49000000.000000,47169843.010000,2023-11-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-08-09,18.537150,121.086380,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735962LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0038,96500000.000000,96500000.000000,2024-02-07,TAGEL CORPORATION,1,2023-03-23,18.363270,120.974550,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735961LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0046,96500000.000000,96500000.000000,2024-03-11,TAGEL CORPORATION / E.C.V. CONSTRUCTION,2,2023-04-05,18.132430,121.078310,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735965LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0037,96500000.000000,93386847.090000,2024-03-15,TAGEL CORPORATION / AQUILA CONSTRUCTI...,2,2023-06-22,18.429090,121.189860,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00620802LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0014,82025000.000000,79576285.450000,2023-07-31,ASC CONSTRUCTION & CONCRETE PRODUCTS ...,2,2022-03-31,18.206590,121.376530,Kabugao,18.021500,121.171600

In [4]:
//req 2 - basic validation BALIKAN!!!
// exclude invalid values
//val columns = listOf("MainIsland","Region","Province","LegislativeDistrict","Municipality","DistrictEngineeringOffice","ProjectId","ProjectName","TypeOfWork","FundingYear","ContractId","ApprovedBudgetForContract","ContractCost","ActualCompletionDate","Contractor","ContractorCount","StartDate","ProjectLatitude","ProjectLongitude","ProvincialCapital","ProvincialCapitalLatitude","ProvincialCapitalLongitude")
//
//val cleanDf = df.filter { row ->
//    columns.all{ col -> row[col] != null }
//}
val cleanDf = df.dropNulls()

val cleanCount= cleanDf.count()
println("original count: ${df.count()}")
println("new Count: $cleanCount")

MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,ContractId,ApprovedBudgetForContract,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526268LZ,Construction of Poblacion Flood Contr...,Construction of Flood Mitigation Stru...,2021,21PC0018,96500000.000000,92692943.800000,2022-10-03,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-03-18,18.250910,121.047570,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526368LZ,Construction of Cabicungan Flood Cont...,Construction of Flood Mitigation Stru...,2021,21PC0019,49000000.000000,47521251.300000,2022-11-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.511800,121.078290,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00526369LZ,Construction of Sipa-San Mariano Floo...,Construction of Flood Mitigation Stru...,2021,21PC0010,47423180.000000,45942583.670000,2022-11-28,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.270230,121.420220,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561270LZ,Construction of Sta. Filomena Floodwa...,Construction of Flood Mitigation Stru...,2021,21PC0067,9900000.000000,9900000.000000,2022-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-01,18.535660,121.080200,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 2nd District Engineering Office,P00561652LZ,Construction of Sinigpit Flood Contro...,Construction of Flood Mitigation Stru...,2021,21PC0034,4950000.000000,4950000.000000,2022-09-23,ALEPHNORTH PEAK CONSTRUCTION AND DEVE...,1,2021-12-01,18.527230,121.096812,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526367LZ,Construction of Nabuangan River (Upst...,Construction of Flood Mitigation Stru...,2021,21PB0004,39199819.730000,38292917.460000,2022-09-24,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-02,17.800000,121.315833,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),null,Apayao 1st District Engineering Office,P00526270LZ,Construction of Nabuangan (Upstream) ...,Construction of Flood Mitigation Stru...,2021,21PB0013,82914680.000000,80309010.270000,2023-04-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2021-12-22,17.800278,121.308889,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0005,23519997.480000,22928490.310000,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0004,15678924.680000,15680000.000000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2022,22PB0010,51761907.660000,51762600.000000,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726398LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0009,72375000.000000,72375000.000000,2023-12-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-02-12,17.818642,121.268639,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726655LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0001,24500000.000000,24500000.000000,2023-06-22,GKA ENGINEERING AND CONSTRUCTION,1,2023-02-12,17.799808,121.282278,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00740313LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2023,23P00020,115793907.830000,115800000.000000,2024-02-29,JOMARCANN GENERAL CONSTRUCTION / RODE...,2,2023-04-12,17.819720,121.268330,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620989LZ,Construction of Cabicungan River Basi...,Construction of Flood Mitigation Stru...,2022,22PC0034,49000000.000000,49000000.000000,2022-12-12,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-02-09,18.527890,121.082970,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00640502LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2022,22PC0063,6930000.000000,6827260.010000,2023-09-15,E.C.V. CONSTRUCTION,1,2022-03-25,18.428870,121.189850,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620990LZ,Construction of Sta. Filomena Flood C...,Construction of Flood Mitigation Stru...,2022,22PC0068,49000000.000000,47169843.010000,2023-11-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-08-09,18.537150,121.086380,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735962LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0038,96500000.000000,96500000.000000,2024-02-07,TAGEL CORPORATION,1,2023-03-23,18.363270,120.974550,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735961LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0046,96500000.000000,96500000.000000,2024-03-11,TAGEL CORPORATION / E.C.V. CONSTRUCTION,2,2023-04-05,18.132430,121.078310,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735965LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0037,96500000.000000,93386847.090000,2024-03-15,TAGEL CORPORATION / AQUILA CONSTRUCTI...,2,2023-06-22,18.429090,121.189860,Kabugao,18.021500,121.171600
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00620802LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0014,82025000.000000,79576285.450000,2023-07-31,ASC CONSTRUCTION & CONCRETE PRODUCTS ...,2,2022-03-31,18.206590,121.376530,Kabugao,18.021500,121.171600

original count: 9855
new Count: 9077

In [5]:
val validYearsDf = cleanDf.filter {
    val year = it["FundingYear"] as? Int

    year!=null && year in 2021..2023 }
val validYearsCount = validYearsDf.count()
println(validYearsCount)

println("clean Count: ${cleanDf.count()}")
println("clean Count: ${validYearsCount}")

6698
clean Count: 9077
clean Count: 6698

In [6]:
import java.time.temporal.ChronoUnit
import java.time.temporal.Temporal

val ApprovedBudgetForContract by column<Double>()
val ContractCost by column<Double>()
val StartDate by column<LocalDate>()
val ActualCompletionDate by column<LocalDate>()

val withNewCols = validYearsDf
    .add("CostSavings") {
        ApprovedBudgetForContract - ContractCost
    }
    .add("CompletionDelayDays") {
        val start = StartDate
        val end = ActualCompletionDate
        ChronoUnit.DAYS.between(start, end)
    }
val data = withNewCols
data

MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,ContractId,ApprovedBudgetForContract,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude,CostSavings,CompletionDelayDays
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0005,23519997.480000,22928490.310000,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.021500,121.171600,591507.170000,266
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0004,15678924.680000,15680000.000000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.021500,121.171600,-1075.320000,296
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2022,22PB0010,51761907.660000,51762600.000000,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.021500,121.171600,-692.340000,421
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726398LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0009,72375000.000000,72375000.000000,2023-12-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-02-12,17.818642,121.268639,Kabugao,18.021500,121.171600,0.000000,305
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726655LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0001,24500000.000000,24500000.000000,2023-06-22,GKA ENGINEERING AND CONSTRUCTION,1,2023-02-12,17.799808,121.282278,Kabugao,18.021500,121.171600,0.000000,130
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00740313LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2023,23P00020,115793907.830000,115800000.000000,2024-02-29,JOMARCANN GENERAL CONSTRUCTION / RODE...,2,2023-04-12,17.819720,121.268330,Kabugao,18.021500,121.171600,-6092.170000,323
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620989LZ,Construction of Cabicungan River Basi...,Construction of Flood Mitigation Stru...,2022,22PC0034,49000000.000000,49000000.000000,2022-12-12,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-02-09,18.527890,121.082970,Kabugao,18.021500,121.171600,0.000000,306
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00640502LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2022,22PC0063,6930000.000000,6827260.010000,2023-09-15,E.C.V. CONSTRUCTION,1,2022-03-25,18.428870,121.189850,Kabugao,18.021500,121.171600,102739.990000,539
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620990LZ,Construction of Sta. Filomena Flood C...,Construction of Flood Mitigation Stru...,2022,22PC0068,49000000.000000,47169843.010000,2023-11-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-08-09,18.537150,121.086380,Kabugao,18.021500,121.171600,1830156.990000,463
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735962LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0038,96500000.000000,96500000.000000,2024-02-07,TAGEL CORPORATION,1,2023-03-23,18.363270,120.974550,Kabugao,18.021500,121.171600,0.000000,321
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735961LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0046,96500000.000000,96500000.000000,2024-03-11,TAGEL CORPORATION / E.C.V. CONSTRUCTION,2,2023-04-05,18.132430,121.078310,Kabugao,18.021500,121.171600,0.000000,341
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735965LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0037,96500000.000000,93386847.090000,2024-03-15,TAGEL CORPORATION / AQUILA CONSTRUCTI...,2,2023-06-22,18.429090,121.189860,Kabugao,18.021500,121.171600,3113152.910000,267
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00620802LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0014,82025000.000000,79576285.450000,2023-07-31,ASC CONSTRUCTION & CONCRETE PRODUCTS ...,2,2022-03-31,18.206590,121.376530,Kabugao,18.021500,121.171600,2448714.550000,487
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00726399LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0029,96500000.000000,96481880.320000,2024-04-03,TAGEL CORPORATION,1,2023-05-05,18.225930,121.384330,Kabugao,18.021500,121.171600,18119.680000,334
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00620807LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0007,77200000.000000,77189689.420000,2023-03-20,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-03-31,18.273580,121.418980,Kabugao,18.021500,121.171600,10310.580000,354
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00726402LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0027,96500000.000000,96483381.660000,2023-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-05,18.309590,121.413730,Kabugao,18.021500,121.171600,16618.340000,254
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00726401LZ,Construction of Apayao - Abulug River...,Construction of Flood Mitigation Stru...,2023,23PC0034,86850000.000000,83452531.580000,2023-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-14,18.276720,121.415940,Kabugao,18.021500,121.171600,3397468.420000,245
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00620810LZ,Construction of Pamplona River Basin ...,Construction of Flood Mitigation Stru...,2022,22PC0056,82025000.000000,79564241.950000,2023-10-09,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-03-31,18.343190,121.271930,Kabugao,18.021500,121.171600,2460758.050000,557
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00735964LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0040,96500000.000000,96500000.000000,2024-07-10,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-25,18.270450,121.406353,Kabugao,18.021500,121.171600,0.000000,442
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00726400LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0032,96500000.000000,96493463.880000,2024-03-20,ISNAG BUILDERS & DEV'T. CORPORATION /...,2,2023-05-05,18.267140,121.401740,Kabugao,18.021500,121.171600,6536.120000,320

In [7]:
// https://kotlin.github.io/dataframe/groupby.html#aggregation
val df_1 = data
    .convert("ApprovedBudgetForContract","CostSavings","CompletionDelayDays").with { (it as Number).toDouble() }
    .select("Region", "MainIsland", "ApprovedBudgetForContract", "CostSavings", "CompletionDelayDays")

var groupedByRegion = df_1
    .groupBy("Region", "MainIsland")
    .aggregate{
        sum( "ApprovedBudgetForContract" ) into "TotalBudget"
        median ("CostSavings") into "MedianSavings"
        mean ("CompletionDelayDays") into "AvgDelay"


        //percentage of projects with delays >30 days by Region and MainIsland

        val totalProjects: Double = rowsCount().toDouble()
        val delayAbove30: Double = count { row ->
            val days = row["CompletionDelayDays"] as Double
            days > 30.0
        }.toDouble()
        ((delayAbove30 / totalProjects) * 100.00) into "HighDelayPct"

    }
    .add("EfficiencyScore") {
        val median = it["MedianSavings"] as Double
        val avg = it["AvgDelay"] as Double
        (median/avg)
    }

groupedByRegion

MainIsland,Region,Province,LegislativeDistrict,Municipality,DistrictEngineeringOffice,ProjectId,ProjectName,TypeOfWork,FundingYear,ContractId,ApprovedBudgetForContract,ContractCost,ActualCompletionDate,Contractor,ContractorCount,StartDate,ProjectLatitude,ProjectLongitude,ProvincialCapital,ProvincialCapitalLatitude,ProvincialCapitalLongitude,CostSavings,CompletionDelayDays
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620988LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0005,23519997.480000,22928490.310000,2022-11-02,PRIME MASTER CONST. AND DEV'T. CORP.,1,2022-02-09,17.823889,121.267778,Kabugao,18.021500,121.171600,591507.170000,266
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620472LZ,Construction of Barren River (Upstrea...,Construction of Flood Mitigation Stru...,2022,22PB0004,15678924.680000,15680000.000000,2022-12-22,BAHRAMLEY CONSTRUCTION,1,2022-03-01,17.823889,121.267778,Kabugao,18.021500,121.171600,-1075.320000,296
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00620136LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2022,22PB0010,51761907.660000,51762600.000000,2023-05-30,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-04-04,17.818333,121.268611,Kabugao,18.021500,121.171600,-692.340000,421
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726398LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0009,72375000.000000,72375000.000000,2023-12-14,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-02-12,17.818642,121.268639,Kabugao,18.021500,121.171600,0.000000,305
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00726655LZ,Construction of Barren River (Downstr...,Construction of Revetment,2023,23PB0001,24500000.000000,24500000.000000,2023-06-22,GKA ENGINEERING AND CONSTRUCTION,1,2023-02-12,17.799808,121.282278,Kabugao,18.021500,121.171600,0.000000,130
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CONNER (APAYAO),Apayao 1st District Engineering Office,P00740313LZ,Construction of Barren River (Downstr...,Construction of Flood Mitigation Stru...,2023,23P00020,115793907.830000,115800000.000000,2024-02-29,JOMARCANN GENERAL CONSTRUCTION / RODE...,2,2023-04-12,17.819720,121.268330,Kabugao,18.021500,121.171600,-6092.170000,323
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620989LZ,Construction of Cabicungan River Basi...,Construction of Flood Mitigation Stru...,2022,22PC0034,49000000.000000,49000000.000000,2022-12-12,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-02-09,18.527890,121.082970,Kabugao,18.021500,121.171600,0.000000,306
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00640502LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2022,22PC0063,6930000.000000,6827260.010000,2023-09-15,E.C.V. CONSTRUCTION,1,2022-03-25,18.428870,121.189850,Kabugao,18.021500,121.171600,102739.990000,539
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00620990LZ,Construction of Sta. Filomena Flood C...,Construction of Flood Mitigation Stru...,2022,22PC0068,49000000.000000,47169843.010000,2023-11-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-08-09,18.537150,121.086380,Kabugao,18.021500,121.171600,1830156.990000,463
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735962LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0038,96500000.000000,96500000.000000,2024-02-07,TAGEL CORPORATION,1,2023-03-23,18.363270,120.974550,Kabugao,18.021500,121.171600,0.000000,321
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735961LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0046,96500000.000000,96500000.000000,2024-03-11,TAGEL CORPORATION / E.C.V. CONSTRUCTION,2,2023-04-05,18.132430,121.078310,Kabugao,18.021500,121.171600,0.000000,341
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),CALANASAN (BAYAG) (APAYAO),Apayao 2nd District Engineering Office,P00735965LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0037,96500000.000000,93386847.090000,2024-03-15,TAGEL CORPORATION / AQUILA CONSTRUCTI...,2,2023-06-22,18.429090,121.189860,Kabugao,18.021500,121.171600,3113152.910000,267
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00620802LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0014,82025000.000000,79576285.450000,2023-07-31,ASC CONSTRUCTION & CONCRETE PRODUCTS ...,2,2022-03-31,18.206590,121.376530,Kabugao,18.021500,121.171600,2448714.550000,487
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),PUDTOL (APAYAO),Apayao 2nd District Engineering Office,P00726399LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0029,96500000.000000,96481880.320000,2024-04-03,TAGEL CORPORATION,1,2023-05-05,18.225930,121.384330,Kabugao,18.021500,121.171600,18119.680000,334
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00620807LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2022,22PC0007,77200000.000000,77189689.420000,2023-03-20,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-03-31,18.273580,121.418980,Kabugao,18.021500,121.171600,10310.580000,354
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00726402LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0027,96500000.000000,96483381.660000,2023-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-05,18.309590,121.413730,Kabugao,18.021500,121.171600,16618.340000,254
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),SANTA MARCELA (APAYAO),Apayao 2nd District Engineering Office,P00726401LZ,Construction of Apayao - Abulug River...,Construction of Flood Mitigation Stru...,2023,23PC0034,86850000.000000,83452531.580000,2023-12-15,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-14,18.276720,121.415940,Kabugao,18.021500,121.171600,3397468.420000,245
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00620810LZ,Construction of Pamplona River Basin ...,Construction of Flood Mitigation Stru...,2022,22PC0056,82025000.000000,79564241.950000,2023-10-09,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2022-03-31,18.343190,121.271930,Kabugao,18.021500,121.171600,2460758.050000,557
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00735964LZ,Construction of Flood Control Structu...,Construction of Flood Mitigation Stru...,2023,23PC0040,96500000.000000,96500000.000000,2024-07-10,ASC CONSTRUCTION & CONCRETE PRODUCTS,1,2023-04-25,18.270450,121.406353,Kabugao,18.021500,121.171600,0.000000,442
Luzon,Cordillera Administrative Region,Apayao,APAYAO (LEGISLATIVE DISTRICT),LUNA (APAYAO),Apayao 2nd District Engineering Office,P00726400LZ,Construction of Apayao-Abulug River B...,Construction of Flood Mitigation Stru...,2023,23PC0032,96500000.000000,96493463.880000,2024-03-20,ISNAG BUILDERS & DEV'T. CORPORATION /...,2,2023-05-05,18.267140,121.401740,Kabugao,18.021500,121.171600,6536.120000,320

Region,MainIsland,TotalBudget,MedianSavings,AvgDelay,HighDelayPct,EfficiencyScore
Cordillera Administrative Region,Luzon,11716720926.290005,2072.120000,234.748899,100.000000,8.826964
National Capital Region,Luzon,34512858340.750010,286227.210000,272.116715,99.855908,1051.854570
Region I,Luzon,23331355341.590008,2332.970000,227.151899,98.553345,10.270528
Region II,Luzon,20227511049.350002,10000.000000,248.870000,100.000000,40.181621
Region III,Luzon,60816863675.419980,2215.650000,212.897706,100.000000,10.407111
Region IV-A,Luzon,32433450465.209995,581.540000,257.522222,100.000000,2.258213
Region IV-B,Luzon,21123321654.840000,2973.580000,259.819113,99.658703,11.444809
Region IX,Mindanao,3377302460.310000,30006.930000,305.282051,100.000000,98.292480
Region V,Luzon,40386863421.270035,240.950000,236.955385,100.000000,1.016858
Region VI,Visayas,18050187896.440002,650.650000,308.705234,100.000000,2.107674
Region VII,Visayas,25790800258.260000,29.030000,245.266968,99.773756,0.118361
Region VIII,Visayas,16898327608.319994,55157.440000,247.755906,100.000000,222.628154
Region X,Mindanao,19013059584.800000,3642.220000,340.241379,100.000000,10.704812
Region XI,Mindanao,15224989180.300005,16.195000,276.520161,100.000000,0.058567
Region XII,Mindanao,10690650674.099998,13911.505000,266.139785,100.000000,52.271422
Region XIII,Mindanao,17175416383.910000,228.540000,321.142857,100.000000,0.711646

In [8]:
val df_2 = data
    .convert("ContractCost","CostSavings").with { (it as Number).toDouble() }
    .select("Contractor", "ContractCost", "ContractorCount","CompletionDelayDays", "CostSavings")
    .split("Contractor").by("/ ".toRegex()).intoRows()
    .update("ContractCost").with {
        val cost = (ContractCost as Number).toDouble()
        val count = (ContractorCount as Number).toDouble()

        if (count == 0.0)
            0.0
        else
            cost / count
    }

val groupedByContractor = df_2
    .groupBy("Contractor")
    .aggregate{
        sum("ContractCost") into "TotalCost"
        count() into "NumProjects"
        mean("CompletionDelayDays") into "AvgDelay"
        sum("CostSavings") into "TotalSavings"
    }
    .add("ReliabilityIndex") {
        val avgDelay = it["AvgDelay"] as? Double?:0.0
        val totalSavings = it["TotalSavings"] as? Double?:0.0
        val totalCost = it["TotalCost"] as? Double?:0.0

        if(totalSavings != 0.0) {
            val value = (1 - (avgDelay / 90.0)) * (totalSavings / totalCost) * 100.0
            if (value > 100.0) 100.0
            else value
        }
        else
            0.0
    }
    .add("RiskFlag"){
        val index = it["ReliabilityIndex"] as? Double?: 0.0
        if (index<50.0) "High Risk"
        else "Low Risk"
    }
    .convert("TotalCost").with { (it as Number).toDouble()}
    .filter {
        (it["NumProjects"] as Int) >= 5
    }
    .sortByDesc("TotalCost")
    .take(15)
    .add("Rank") { it.index() + 1}
    .select("Rank","Contractor", "TotalCost", "NumProjects", "AvgDelay", "TotalSavings", "ReliabilityIndex", "RiskFlag")


println(groupedByContractor)
groupedByContractor
//print(df_2)
//print(new)

    Rank                               Contractor         TotalCost NumProjects   AvgDelay     TotalSavings ReliabilityIndex  RiskFlag
  0    1 LEGACY CONSTRUCTION CORPORATION (FORM... 7446448535.564999         105 287.228571   7032187.790000        -0.206952 High Risk
  1    2                              QM BUILDERS 5648722004.645001          78 234.076923   2915176.150000        -0.082616 High Risk
  2    3 SUNWEST, INC. (FORMERLY: SUNWEST CONS... 5532149681.809999          41 315.512195  16880375.390000        -0.764567 High Risk
  3    4 ALPHA & OMEGA GEN. CONTRACTOR & DEVEL... 5105695778.405001          87 284.206897  69750620.290000        -2.947917 High Risk
  4    5     ST. TIMOTHY CONSTRUCTION CORPORATION 4914578423.269998          85 273.670588  60502107.260000        -2.512357 High Risk
  5    6 HI-TONE CONSTRUCTION & DEVELOPMENT CO... 3875955185.570001          52 262.826923  52821615.510000        -2.616989 High Risk
  6    7 ROYAL CROWN MONARCH CONSTRUCTION & SU... 3556840641.550000          39 284.487179  44571321.820000        -2.707943 High Risk
  7    8 CENTERWAYS CONSTRUCTION AND DEVELOPME... 3517050892.675001          58 292.224138 398623788.850000       -25.466839 High Risk
  8    9          EQUI-PARCO CONSTRUCTION COMPANY 3505279348.530000          33 411.909091  68512048.150000        -6.990932 High Risk
  9   10                L.R. TIQUI BUILDERS, INC. 3488101585.370000          41 316.951220  39756779.660000        -2.874168 High Risk
 10   11 EGB CONSTRUCTION CORPORATION (FORMERL... 3365906558.375001          71 269.464789   9456950.720000        -0.560255 High Risk
 11   12                  MG SAMIDAN CONSTRUCTION 3318694600.679999          44 232.977273   3785590.200000        -0.181214 High Risk
 12   13 ST. MATTHEW GEN. CONTRACTOR & DEVELOP... 3288273330.495000          52 284.250000  21070994.210000        -1.383043 High Risk
 13   14 TRIPLE 8 CONSTRUCTION & SUPPLY, INC. ... 3037595030.765000          44 255.772727  53724445.670000        -3.257712 High Risk
 14   15 GREAT PACIFIC BUILDERS AND GEN. CONTR... 2863779436.580000          39 288.384615  10859041.900000        -0.835829 High Risk

Rank,Contractor,TotalCost,NumProjects,AvgDelay,TotalSavings,ReliabilityIndex,RiskFlag
1,LEGACY CONSTRUCTION CORPORATION (FORM...,7446448535.564999,105,287.228571,7032187.790000,-0.206952,High Risk
2,QM BUILDERS,5648722004.645001,78,234.076923,2915176.150000,-0.082616,High Risk
3,"SUNWEST, INC. (FORMERLY: SUNWEST CONS...",5532149681.809999,41,315.512195,16880375.390000,-0.764567,High Risk
4,ALPHA & OMEGA GEN. CONTRACTOR & DEVEL...,5105695778.405001,87,284.206897,69750620.290000,-2.947917,High Risk
5,ST. TIMOTHY CONSTRUCTION CORPORATION,4914578423.269998,85,273.670588,60502107.260000,-2.512357,High Risk
6,HI-TONE CONSTRUCTION & DEVELOPMENT CO...,3875955185.570001,52,262.826923,52821615.510000,-2.616989,High Risk
7,ROYAL CROWN MONARCH CONSTRUCTION & SU...,3556840641.550000,39,284.487179,44571321.820000,-2.707943,High Risk
8,CENTERWAYS CONSTRUCTION AND DEVELOPME...,3517050892.675001,58,292.224138,398623788.850000,-25.466839,High Risk
9,EQUI-PARCO CONSTRUCTION COMPANY,3505279348.530000,33,411.909091,68512048.150000,-6.990932,High Risk
10,"L.R. TIQUI BUILDERS, INC.",3488101585.370000,41,316.951220,39756779.660000,-2.874168,High Risk
11,EGB CONSTRUCTION CORPORATION (FORMERL...,3365906558.375001,71,269.464789,9456950.720000,-0.560255,High Risk
12,MG SAMIDAN CONSTRUCTION,3318694600.679999,44,232.977273,3785590.200000,-0.181214,High Risk
13,ST. MATTHEW GEN. CONTRACTOR & DEVELOP...,3288273330.495000,52,284.250000,21070994.210000,-1.383043,High Risk
14,"TRIPLE 8 CONSTRUCTION & SUPPLY, INC. ...",3037595030.765000,44,255.772727,53724445.670000,-3.257712,High Risk
15,GREAT PACIFIC BUILDERS AND GEN. CONTR...,2863779436.580000,39,288.384615,10859041.900000,-0.835829,High Risk

In [9]:
val df_3 = data
    .convert("CostSavings").with { (it as Number).toDouble() }
    .select("FundingYear", "TypeOfWork", "CostSavings")
var groupedByYear = df_3
    .groupBy("FundingYear", "TypeOfWork")
    .aggregate {
        count() into "TotalProjects"
        mean("CostSavings") into "AvgSavings"
        val overrunCount = filter {
            val savings = it["CostSavings"] as Double
            savings<0.0
        }.count().toDouble()
        val totalCount = count()
        overrunCount / totalCount  into "OverrunRate"
    }

// cyurrent-previous/previous/100

val baselineDf = groupedByYear
    .filter{
        (it["FundingYear"] as Int)  == 2021
    }
    .select ("TypeOfWork","AvgSavings")
    .rename("AvgSavings").into("BaseLineAvgSavings")

val df_3WithYOY = groupedByYear
    .leftJoin(baselineDf) { column<String>("TypeOfWork") }
    .add ("YoYChange") {
        val curr = it["AvgSavings"] as? Double
        val baseline = it["BaseLineAvgSavings"] as? Double

        if(curr!=null && baseline!=null && baseline!=0.0)
            (curr - baseline)/baseline * 100.00
        else
            null
    }
    .select (
        "FundingYear",
        "TypeOfWork",
        "TotalProjects",
        "AvgSavings",
        "OverrunRate",
        "YoYChange",
    )
    .sortBy("FundingYear")
    .sortByDesc("AvgSavings")

print(df_3WithYOY.rows().toDataFrame())

Rank,Contractor,TotalCost,NumProjects,AvgDelay,TotalSavings,ReliabilityIndex,RiskFlag
1,LEGACY CONSTRUCTION CORPORATION (FORM...,7446448535.564999,105,287.228571,7032187.790000,-0.206952,High Risk
2,QM BUILDERS,5648722004.645001,78,234.076923,2915176.150000,-0.082616,High Risk
3,"SUNWEST, INC. (FORMERLY: SUNWEST CONS...",5532149681.809999,41,315.512195,16880375.390000,-0.764567,High Risk
4,ALPHA & OMEGA GEN. CONTRACTOR & DEVEL...,5105695778.405001,87,284.206897,69750620.290000,-2.947917,High Risk
5,ST. TIMOTHY CONSTRUCTION CORPORATION,4914578423.269998,85,273.670588,60502107.260000,-2.512357,High Risk
6,HI-TONE CONSTRUCTION & DEVELOPMENT CO...,3875955185.570001,52,262.826923,52821615.510000,-2.616989,High Risk
7,ROYAL CROWN MONARCH CONSTRUCTION & SU...,3556840641.550000,39,284.487179,44571321.820000,-2.707943,High Risk
8,CENTERWAYS CONSTRUCTION AND DEVELOPME...,3517050892.675001,58,292.224138,398623788.850000,-25.466839,High Risk
9,EQUI-PARCO CONSTRUCTION COMPANY,3505279348.530000,33,411.909091,68512048.150000,-6.990932,High Risk
10,"L.R. TIQUI BUILDERS, INC.",3488101585.370000,41,316.951220,39756779.660000,-2.874168,High Risk
11,EGB CONSTRUCTION CORPORATION (FORMERL...,3365906558.375001,71,269.464789,9456950.720000,-0.560255,High Risk
12,MG SAMIDAN CONSTRUCTION,3318694600.679999,44,232.977273,3785590.200000,-0.181214,High Risk
13,ST. MATTHEW GEN. CONTRACTOR & DEVELOP...,3288273330.495000,52,284.250000,21070994.210000,-1.383043,High Risk
14,"TRIPLE 8 CONSTRUCTION & SUPPLY, INC. ...",3037595030.765000,44,255.772727,53724445.670000,-3.257712,High Risk
15,GREAT PACIFIC BUILDERS AND GEN. CONTR...,2863779436.580000,39,288.384615,10859041.900000,-0.835829,High Risk

    FundingYear                               TypeOfWork TotalProjects     AvgSavings OverrunRate YoYChange
  0        2022 Rehabilitation / Major Repair of Floo...             1 4370780.740000    0.000000      null
  1        2022 Construction of Flood Mitigation Stru...          2015 1200216.386943    0.098759      null
  2        2023 Rehabilitation / Major Repair of Floo...           217 1100949.326175    0.069124      null
  3        2023 Construction of Flood Mitigation Faci...            74 1010904.891216    0.175676      null
  4        2022 Rehabilitation / Major Repair of Floo...           246  951959.764715    0.154472      null
  5        2023 Construction of Flood Mitigation Stru...          2256  905259.825106    0.078901      null
  6        2022 Construction of Slope Protection Stru...           308  898843.608214    0.074675      null
  7        2022 Rehabilitation / Major Repair of Slop...            16  841782.912500    0.062500      null
  8        2022 Construction of Flood Mitigation Faci...            43  829713.740930    0.209302      null
  9        2022       Construction of Drainage Structure           215  784631.276326    0.088372      null
 10        2022                     Construction of Dike            76  772732.762105    0.065789      null
 11        2023 Rehabilitation / Major Repair of Slop...            14  768840.893571    0.000000      null
 12        2022               Construction of Groundsill             2  752371.180000    0.000000      null
 13        2023 Rehabilitation / Major Repair of Floo...             5  742935.052000    0.000000      null
 14        2023 Rehabilitation / Major Repair of Drai...            71  609033.106197    0.000000      null
 15        2023 Construction of Slope Protection Stru...           196  547223.534490    0.056122      null
 16        2023                Construction of Revetment           234  530128.276154    0.025641      null
 17        2022 Rehabilitation / Major Repair of Drai...            84  461093.029643    0.071429      null
 18        2022                Construction of Revetment           269  460817.616171    0.018587      null
 19        2023                 Construction of Waterway             1  356123.390000    0.000000      null
...